### ISSUE TITLE
How to export csv data result pivot?

### ISSUE THREAD

**Issue by NandaRusfikri** [MarketConnect/vue-pivot-table#3]
after drag drop colums row ..... how to download to csv

**Comment by Owumaro** [comment]
Apologies for the super late answer. I guess you already found a solution but I will reply here in case someone else needs this.

The answer is... Use any csv library 😄 But from my experience, some libraries don't handle colspans/rowspans and will mess up.
I recommend this library: https://github.com/SheetJS/js-xlsx

Here is a code sample (assuming your pivot table component has the id `pivotTable`):
```
import XLSX from 'xlsx'
const wb = XLSX.utils.table_to_book(document.querySelector('#pivotTable table'))
XLSX.writeFile(wb, 'out.csv')
```
