### ISSUE TITLE
how change variable in reduce function

### ISSUE THREAD

**Issue by lalo4ka** [MarketConnect/vue-pivot-table#5]
is possible change dynamically the variable  in reducer function?
reducer: (sum, item) => sum + item.count

**Comment by antoinematyja** [comment]
Yes, you can set the `reducer` prop of the component to a method that will reduce values depending on whatever you want.
Here is an example of what you could do :
```js
data: {
  reduceAttr: 'count' // Can be set to 'sum', 'average' or 'count' by the user
},
methods: {
  reduce: function(sum, item) {
    return sum + item[this.reduceAttr]
  }
}
```
