### ISSUE TITLE
How to remove 'show settings' button?

### ISSUE THREAD

**Issue by titoesteves** [MarketConnect/vue-pivot-table#6]
How can I disable or remove the 'show settings' button? ![](https://i.imgur.com/0oKMIsS.png)

**Comment by antoinematyja** [comment]
If you don't need the settings, you should use directly the `PivotTable` component.
`Pivot` component = Settings UI + `PivotTable` component

They almost share the same API. See https://github.com/MarketConnect/vue-pivot-table#pivot--pivottable
