### ISSUE TITLE
How to update rows and columns

### ISSUE THREAD

**Issue by erailea** [MarketConnect/vue-pivot-table#8]
How can I update rows and columns programmatically? It doesn't support or should it be enough that changing models. I set my rows and columns model with my report data but it doesn't seem effective at all.

**Comment by antoinematyja** [comment]
Hi,
Sorry for the late reply. If this issue is still relevant, please give me more information about it :
- Which component are you using (Pivot or PivotTable) ?
- Which properties are you updating ?
Thanks
